In [21]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import pandas as pd
from sklearn.decomposition import PCA

In [1]:
# Inpiration https://towardsdatascience.com/a-simple-explanation-of-the-bag-of-words-model-b88fc4f4971

### Bag of Words

In [9]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
 
sentence_1="Our Deeds are the Reason of this earthquake May God beat us more for our Karma."
sentence_2="Our Karma is not good and Karma is nothing but deed. God is not responsible."
 
 
 
CountVec = CountVectorizer(ngram_range=(1,1), # to use bigrams ngram_range=(2,2)
                           stop_words='english')
#transform
Count_data = CountVec.fit_transform([sentence_1,sentence_2])
 
#create dataframe
cv_dataframe=pd.DataFrame(Count_data.toarray(),columns=CountVec.get_feature_names())
print(cv_dataframe)

   beat  deed  deeds  earthquake  god  good  karma  reason  responsible
0     1     0      1           1    1     0      1       1            0
1     0     1      0           0    1     1      2       0            1


d:\Users\admin\anaconda3\envs\sanskrit\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [4]:
file='Cleaned-Twitter.csv'
df = pd.read_csv(file)

In [7]:
df.iloc[0]['text']

'Our Deeds are the Reason of this earthquake May ALLAH Forgive us all'

### TFIDF Vector

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
       'This is the first document.',
       'This document is the second document.',
       'And this is the third one.',
       'Is this the first document?',
   ]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names_out()


array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)

In [13]:
df      = pd.read_csv(file)
df_full = pd.read_csv(file)

list_corpus      = df["text"].tolist()
list_corpus_full = df_full["text"].tolist()

In [14]:
tfidf_vectorizer = TfidfVectorizer(max_features=300, ngram_range=(1,2) )

emb = tfidf_vectorizer.fit_transform(df['text']) 

def tfidf_vec(data):
    tfidf_vectorizer = TfidfVectorizer(max_features=300, ngram_range=(1,2) )

    emb = tfidf_vectorizer.fit_transform(data)

    return emb, tfidf_vectorizer

In [38]:
#help(TfidfVectorizer)

In [15]:
embed_tfidf, vec_tfidf   = tfidf_vec(list_corpus_full)

embed_tfidf  = embed_tfidf.todense()

In [16]:
embed_tfidf.shape

(7610, 300)

In [17]:
#df.iloc[0,1]

In [18]:
embed_tfidf[0]

matrix([[0.        , 0.        , 0.        , 0.        , 0.32868119,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.29736785,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.4554877 , 0.        , 0.        ,
         0.        , 0.        , 0

In [22]:
pca = PCA(n_components=15)
embed_tfidf  = pca.fit_transform(embed_tfidf)

embed_tfidf          = pd.DataFrame(embed_tfidf, index=df_full.index)

d:\Users\admin\anaconda3\envs\sanskrit\lib\site-packages\sklearn\utils\validation.py:598: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  FutureWarning,


In [23]:
embed_tfidf.shape

(7610, 15)

In [24]:
embed_tfidf.head(5)

0         1         2         3         4         5         6   \
0  0.124003 -0.051135  0.099157 -0.015947  0.015310 -0.035803 -0.076231   
1 -0.100867 -0.020499  0.064507 -0.071436 -0.053976 -0.036469  0.050117   
2 -0.078903  0.250932 -0.067893  0.083065 -0.058727 -0.059212 -0.053616   
3 -0.091169  0.216799  0.020647 -0.057901 -0.021135 -0.001490 -0.025755   
4 -0.118222 -0.046835  0.059447 -0.040849 -0.010223 -0.022753 -0.039461   

         7         8         9         10        11        12        13  \
0  0.025651  0.017077 -0.003326 -0.003818 -0.002022 -0.018459 -0.006149   
1 -0.007321 -0.003451 -0.009432 -0.039783 -0.025142 -0.053898 -0.000768   
2 -0.050516  0.046973 -0.070049  0.137217  0.008557  0.080345  0.026153   
3 -0.021277 -0.017611 -0.008904 -0.008622 -0.025747  0.002425 -0.006991   
4  0.038031 -0.095381 -0.029771 -0.087953 -0.029807 -0.208687  0.187833   

         14  
0 -0.029510  
1 -0.097997  
2 -0.012518  
3 -0.096645  
4  0.230075

### BOW Vector

In [25]:
def bow_vec(data):
    count_vectorizer = CountVectorizer(max_features=300, ngram_range=(1,1) )

    emb = count_vectorizer.fit_transform(data)

    return emb, count_vectorizer

In [29]:
embed_bow, vec_bow = bow_vec(list_corpus_full)
embed_bow = embed_bow.todense()
embed_bow.shape

(7610, 300)

In [32]:
embed_bow[0]

matrix([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
         0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [26]:


pca = PCA(n_components=15)
embed_bow = pca.fit_transform(embed_bow)

embed_bow = pd.DataFrame(embed_bow, index=df_full.index)

d:\Users\admin\anaconda3\envs\sanskrit\lib\site-packages\sklearn\utils\validation.py:598: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  FutureWarning,


In [27]:
embed_bow.shape

(7610, 15)

In [12]:
embed_bow.to_csv(r"\embedding_bow.csv")

In [13]:
embed_bow.head(5)

0         1         2         3         4         5         6   \
0  0.648325 -0.372389 -0.337110  0.560750 -0.023368  0.213378 -0.021474   
1 -0.592873 -0.245450 -0.221353 -0.052827 -0.159176 -0.074328 -0.104647   
2 -0.198350  0.510601  1.830383 -0.052009 -0.374736  0.174252 -0.126010   
3 -0.502374 -0.379008  0.742974 -0.095465 -0.151257 -0.029165 -0.088930   
4 -0.556155 -0.166580 -0.200648 -0.019061 -0.033172 -0.064355  0.121216   

         7         8         9         10        11        12        13  \
0 -0.100306 -0.039614  0.047266 -0.150941  0.044855  0.005031  0.016368   
1  0.059738 -0.104205 -0.053962 -0.012184 -0.016305 -0.059550 -0.103953   
2  0.002092 -0.131043 -0.130586 -0.102571 -0.079316  0.575990  0.171815   
3 -0.053088 -0.067557 -0.073817 -0.022631  0.005500  0.008641 -0.051615   
4 -0.100040 -0.041033  0.046747 -0.129987 -0.125644 -0.059882 -0.564723   

         14  
0  0.086918  
1 -0.064446  
2  0.407271  
3  0.004334  
4 -0.272394

### Word2Vec

In [14]:
from gensim.models import Word2Vec
import pandas as pd
import nltk
import numpy as np

In [15]:
# Set values for various parameters
feature_size = 15    # Word vector dimensionality  
window_context = 20  # Context window size                                                                                    
min_word_count = 1   # Minimum word count                        
sample = 1e-3        # Downsample setting for frequent words
sg = 1               # skip-gram model

In [ ]:
import pandas as pd 
df= pd.read_csv(file)
corpus = list(df['text'])
tokenized_corpus = [nltk.word_tokenize(doc) for doc in corpus]
df['text_tkn'] = tokenized_corpus


#This is required to create word embedding of full dataset
df_full =pd.read_csv(file)
corpus_full = list(df_full['text'])
tokenized_corpus_full = [nltk.word_tokenize(doc) for doc in corpus_full]
df_full['sentence_tkn'] = tokenized_corpus_full

In [ ]:
embedding_model = Word2Vec(tokenized_corpus, vector_size=feature_size, 
                                  window=window_context, min_count = min_word_count,
                                  sg=sg, sample=sample, epochs=5)
vocabulary = set(embedding_model.wv.index_to_key )

In [35]:
def average_word_vectors(words, model, vocabulary, num_features):
    feature_vector = np.zeros((num_features,),dtype="float64")
    nwords = 0.
    for word in words:
        if word in vocabulary: 
            nwords = nwords + 1.
            feature_vector = np.add(feature_vector, model.wv[word])
    if nwords:
        feature_vector = np.divide(feature_vector, nwords)
    return feature_vector

def averaged_word_vectorizer(corpus, model, num_features):
    
    features = [average_word_vectors(tokenized_sentence, model, vocabulary, num_features)
                    for tokenized_sentence in corpus]
    return np.array(features)

In [36]:
# get document level embeddings
w2v_doc_features = averaged_word_vectorizer(corpus=tokenized_corpus_full, model=embedding_model,
                                             num_features=feature_size)
df_w2v = pd.DataFrame(w2v_doc_features)

In [37]:
df_w2v

0         1         2         3         4         5         6   \
0    -0.463541  0.385192  0.615906 -0.511017  0.451790  0.181643  0.329359   
1    -0.556738  0.055004  0.514086 -0.259937  0.654891 -0.443765  0.298363   
2    -0.586281  0.288485  0.806471 -0.449322  0.576510  0.114640  0.415376   
3    -0.662422  0.174502  0.649841 -0.252678  0.693505 -0.198109  0.378553   
4    -0.585272  0.397375  1.009378 -0.458882  0.497112 -0.045452  0.472325   
...        ...       ...       ...       ...       ...       ...       ...   
7605 -0.868954  0.313230  1.242468 -0.350825  0.873842 -0.358923  0.338369   
7606 -0.717047  0.381327  0.771373 -0.401854  0.692056  0.041093  0.248938   
7607 -0.437679  0.321830  0.026815 -0.422229  0.928994 -0.372119  0.355659   
7608 -0.421805  0.263361  0.792902 -0.352236  0.573006 -0.296036  0.371975   
7609 -1.177398  0.249381  0.235386 -0.283408  1.716153 -0.458434  0.167347   

            7         8         9         10        11        12        13  \
0    -0.200348 -0.437826 -0.489277  0.321815  0.449759 -0.164279 -0.633994   
1     0.097618 -0.499772 -0.241564  0.571624  0.468145 -0.295232 -0.435764   
2    -0.135801 -0.491195 -0.429666  0.416134  0.653691 -0.078418 -0.808905   
3     0.160439 -0.307674 -0.401286  0.544405  0.597655 -0.226909 -0.683569   
4    -0.383114 -0.330647 -0.393039  0.405480  0.712295 -0.071999 -0.623767   
...        ...       ...       ...       ...       ...       ...       ...   
7605 -0.125452 -0.161789 -0.384963  0.648030  0.569826  0.096923 -0.702922   
7606  0.054199 -0.259814 -0.443346  0.737303  0.559491 -0.266619 -0.812245   
7607 -0.012871 -0.304681 -0.423134  0.316804  0.211306 -0.380352 -0.126631   
7608 -0.131402 -0.317929 -0.331936  0.373273  0.645215 -0.103157 -0.651510   
7609  0.824062 -0.463981 -0.540047  1.545499  0.383048 -0.633807 -0.358082   

            14  
0    -0.174536  
1    -0.155590  
2    -0.276356  
3    -0.288481  
4     0.032724  
...        ...  
7605 -0.224239  
7606 -0.150675  
7607 -0.424571  
7608 -0.217778  
7609 -0.562246  

[7610 rows x 15 columns]

# 
- Inspiration https://towardsdatascience.com/different-techniques-to-represent-words-as-vectors-word-embeddings-3e4b9ab7ceb4

### Count Vectorizer or (Document Term Matrix) or BOW

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

sentences = [
    'He is playing in the field.',
    'He is running towards the football.',
    'The football game ended.',
    'It started raining while everyone was playing in the field.'
]

vectorizer = CountVectorizer()
sentence_vectors = vectorizer.fit_transform(sentences)

print(sentence_vectors.toarray())

[[0 0 1 0 0 1 1 1 0 1 0 0 0 1 0 0 0]
 [0 0 0 1 0 1 0 1 0 0 0 1 0 1 1 0 0]
 [1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 1 1 0 0 0 1 0 1 1 1 0 1 1 0 1 1]]


### TFIDF

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

sentences = [
    'He is playing in the field.',
    'He is running towards the football.',
    'The football game ended.',
    'It started raining while everyone was playing in the field.'
]

vectorizer = TfidfVectorizer(norm = False, smooth_idf = False)
sentence_vectors = vectorizer.fit_transform(sentences)
print(sentence_vectors.toarray())

[[0.         0.         1.69314718 0.         0.         1.69314718
  1.69314718 1.69314718 0.         1.69314718 0.         0.
  0.         1.         0.         0.         0.        ]
 [0.         0.         0.         1.69314718 0.         1.69314718
  0.         1.69314718 0.         0.         0.         2.38629436
  0.         1.         2.38629436 0.         0.        ]
 [2.38629436 0.         0.         1.69314718 2.38629436 0.
  0.         0.         0.         0.         0.         0.
  0.         1.         0.         0.         0.        ]
 [0.         2.38629436 1.69314718 0.         0.         0.
  1.69314718 0.         2.38629436 1.69314718 2.38629436 0.
  2.38629436 1.         0.         2.38629436 2.38629436]]


### Hashing Vectorizer

In [9]:
from sklearn.feature_extraction.text import HashingVectorizer

sentences = [
    'He is playing in the field.',
    'He is running towards the football.',
    'The football game ended.',
    'It started raining while everyone was playing in the field.'
]

vectorizer = HashingVectorizer(norm = None, n_features = 17)
sentence_vectors = vectorizer.fit_transform(sentences)
print(sentence_vectors.toarray())

[[ 0.  1.  0.  0.  1.  0.  0.  0.  1.  0.  0. -1. -1.  0.  0.  1.  0.]
 [ 1.  1.  0.  0.  1.  0.  0.  0.  1.  0.  0. -2.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0. -1.  0.  0.  0. -1.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  0.  0. -1.  0.  0.  0. -1. -1. -2.  0. -1.  1.  0.]]


### Word2Vec

In [1]:
from gensim.models import word2vec

sentences = [
    'He is playing in the field.',
    'He is running towards the football.',
    'The football game ended.',
    'It started raining while everyone was playing in the field.'
]

for i, sentence in enumerate(sentences):
	tokenized= []
	for word in sentence.split(' '):
		word = word.split('.')[0]
		word = word.lower()
		tokenized.append(word)
	sentences[i] = tokenized


In [8]:

model = word2vec.Word2Vec(sentences, workers = 1, vector_size= 2, min_count = 1, window = 3, sg = 0)
similar_word = model.wv.most_similar('football')[0]
print("Most common word to football is: {}".format(similar_word[0]))

## Output
# Most common word to football is: game

Most common word to football is: is
